---

datafile: 'data/projects_2012_2013.csv'
outcome_var: 'fullyfunded_within_60days'

parameters:
  LR:
    C: [0.001, 0.01, 0.1]
    penalty: ['l1', 'l2']
  
  NN:
    n_neighbors: [1, 9]
  
  DT:
    max_depth: [1, 10]
  
  SVM:
    kernel: ['linear']
    C: [0.001, 1]
    probability: [True]
    random_state: 0
  
  RF:
    max_depth: [1, 50]
    n_estimators: [10, 100]
    max_features: [1, 0.75, 0.5]

