---
# Dataset
data_dir: './data/'
datafile: 'projects_2012_2013.csv'
outcome_var: 'fullyfunded_within_60days'
features: ['school_latitude', 'school_longitude', 'school_state',
           'school_metro', 'school_charter', 'school_magnet',
           'teacher_prefix', 'primary_focus_subject', 'primary_focus_area',
           'resource_type', 'poverty_level', 'grade_level',
           'total_price_including_optional_support',
           'students_reached', 'eligible_double_your_impact_match',
           'date_posted', 'datefullyfunded']
time_format: '%m/%d/%y'
time_features:
  start: 'date_posted'
  end: 'datefullyfunded'

# Temporal Validation
data_start_date: '2012-01-01 00:00:00'
start_dates: ['2012-07-01', '2013-01-01', '2013-07-01']
test_train_gap: ['days', 60]
test_month_size: 6
time_column: 'date_posted'

# Preprocessing
drop_vars: ['projectid', 'date_posted', 'datefullyfunded']

datatypes:
  float: []
  Int64: ['students_reached']
  object: []
  time: ['date_posted', 'datefullyfunded']

feature_types:
  categorical: ['school_state', 'school_metro', 'school_charter',
                'school_magnet', 'teacher_prefix', 'primary_focus_subject',
                'primary_focus_area', 'resource_type', 'poverty_level',
                'grade_level', 'eligible_double_your_impact_match']
  continuous: []

test_size: 0.3
random_state: 10
threshold: 0.5
PR_thold: [1, 2, 5, 10, 20, 30, 50]
models: ['Baseline', 'LR', 'KNN', 'DT', 'SVM', 'RF', 'BG']
metrics: ['Accuracy', 'F1', 'ROC_AUC', 'Precision_at_1%', 'Recall_at_1%',
          'Precision_at_2%', 'Recall_at_2%','Precision_at_5%', 'Recall_at_5%',
          'Precision_at_10%', 'Recall_at_10%','Precision_at_20%',
          'Recall_at_20%','Precision_at_30%', 'Recall_at_30%',
          'Precision_at_50%', 'Recall_at_50%']
tuning: 'precision'
final_metric: 'Precision_at_5%'

parameters:

  Baseline:
    strategy: ['uniform']

  LR:
    solver: ['liblinear']
    C: [0.01, 0.1, 1, 10, 20, 50]
    penalty: ['l1', 'l2']
    random_state: [10]
  
  KNN:
    n_neighbors: [1, 2, 4, 5, 10, 50]
    weights: ['uniform', 'distance']
    metric: ["euclidean", "manhattan"]
  
  DT:
    criterion: ['gini', 'entropy']
    max_depth: [2, 5, 10, 20, 30, 50]
    max_features: [2, 5, 10, 15, 20]
    random_state: [10]

  SVM:
    C: [0.01, 0.1, 1, 10, 50]
    penalty: ['l1', 'l2']
    loss: ['squared_hinge']
    dual: [False]
    random_state: [10]
  
  RF:
    max_features: [2, 5, 10, 20, 30, 50]
    random_state: [10]

  AB:
    algorithm: ['SAMME', 'SAMME.R']
    n_estimators: [1, 2, 5, 10]
    learning_rate: [0.01, 0.1, 1, 10]
    random_state: [10]
  
  BG:
    max_samples: [0.001, 0.01, 0.05, 0.1]
    n_estimators: [1, 2, 5, 10]
    random_state: [10]
